apiVersion: v1
kind: Service
metadata:
  name: twtr-be-service
spec:
  selector:
    app: twtr-be
  ports:
    - protocol: TCP
      port: 5000  # Exposed port within the cluster
      targetPort: 5000  # Port your backend service is listening on
  type: NodePort