apiVersion: v1
kind: Service
metadata:
  name: sa-frontend-service
spec:
  type: NodePort
  selector:
    app: sa-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30002