apiVersion: v1
kind: Service
metadata:
  name: twtr-redis-service
spec:
  selector:
    app: twtr-redis
  ports:
    - protocol: TCP
      port: 6379  # Exposed Redis port within the cluster
      targetPort: 6379  # Port Redis is listening on inside the container
  clusterIP: None  # Headless service for direct access to Pods
